import {
    Activity,
    Database,
    FolderLock,
    FolderOpen,
    Globe,
    KeyRound,
    Lock,
    Mail,
    MailCheck,
    MessageSquare,
    Monitor,
    Plug,
    Share2,
    ShieldCheck,
    Terminal,
    Users,
    Zap,
} from 'lucide-vue-next';
import type { Component } from 'vue';

export const PROTOCOL_ICONS: Record<string, Component> = {
    tcp:      Plug,
    http:     Globe,
    https:    Lock,
    ssh:      Terminal,
    rdp:      Monitor,
    udp:      Zap,
    database: Database,
    ftp:      FolderOpen,
    ftps:     FolderLock,
    smtp:     Mail,
    smtps:    MailCheck,
    icmp:     Activity,
    irc:      MessageSquare,
    smb:      Share2,
    ldap:     Users,
    ldaps:    ShieldCheck,
};
